shell: func to setup AWS MFA

diff --git a/_zshrc b/_zshrc
--- a/_zshrc
+++ b/_zshrc
@@ -46,3 +46,22 @@ alias gestalt='mbzl tool //dropbox/yaps/gestalt'
 alias ad='arc diff origin/master'
 alias al='arc land --onto master --fast-lane'
 alias adl='ad && al'
+
+function awscreds {
+    tokens=/tmp/tokens.json
+    if [ -z "$1" ]
+    then
+        echo "MFA token needed"
+        return 1
+    fi
+    aws sts get-session-token --serial-number arn:aws:iam::495839769800:mfa/ashishg_mfa --token-code $1 > $tokens
+    if ! [ $? -eq '0' ]
+    then
+        echo "Failed to get AWS credentials"
+        return 1
+    fi
+    export AWS_ACCESS_KEY_ID=$(jq -r .Credentials.AccessKeyId $tokens)
+    export AWS_SECRET_ACCESS_KEY=$(jq -r .Credentials.SecretAccessKey $tokens)
+    export AWS_SESSION_TOKEN=$(jq -r .Credentials.SessionToken $tokens)
+    rm $tokens
+}
